// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://msvjechqvhdovnerwcpk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zdmplY2hxdmhkb3ZuZXJ3Y3BrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMzQ1ODAsImV4cCI6MjA1OTcxMDU4MH0.31s9Ha9NkQWDIFfQkx8YdR8-DICmgEFNWIDZpJ08_yM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);